name: pact_dart
description: Dart DSL for Pact, the de-facto API contract testing tool.
version: 1.0.0

environment:
  sdk: '>=3.6.0 <4.0.0'

dependencies:
  ffi: 2.1.3
  path: 1.9.0
  http: 1.2.2
  logging: 1.3.0

dev_dependencies:
  test: 1.25.8

executables:
  install:
